export const SET_APP_TITLE = "SET_APP_TITLE";
export const ADD_RESPONSE = "ADD_RESPONSE";
export const REMOVE_RESPONSE = "REMOVE_RESPONSE";
export const CLEAR_RESPONSES = "CLEAR_RESPONSES";
export const RESET_APP = "RESET_APP";
